# This repository contains a custom Pantheon Upstream used to create and manage
# every site on the YaleSites platform. Out of the box this project is not
# connected to any individual Drupal site. Setting a Pantheon site name and UUID
# allows lando to connect the local dev environment to a Pantheon environment.

# Copy and rename this file to .lando.local.yml and set any site specific
# variables and overrides. The default values in this file will connect to the
# YaleSite's integration environment.

# Set a local name for this application; this can be any value.
name: yalesites-platform
config:
  # 32 alphanumeric Pantheon site UUID.
  id: cb91b104-1d1e-42b7-a3a5-d0f6715e459c
  # Pantheon site name.
  site: yalesites-platform
tooling:
  drush:
    service: appserver
    env:
      # Set base url based on above Lando project 'name'.
      DRUSH_OPTIONS_URI: "https://yalesites-platform.lndo.site/"
services:
  appserver:
    overrides:
      environment:
        COMPOSER_PROCESS_TIMEOUT: 1800
