# Each YaleSite property will have unique environmental variables used to
# connect the local Lando site to the remote website hosted by Pantheon.
# Copy and rename this file to .lando.local.yml and set any site specific
# variables and overrides. The default UUID and site name included in this file
# will connect the local environment to a specific integration environment.

# Set a local name for this application; this can be any value.
name: yalesites-project
config:
  # 32 alphanumeric Pantheon site UUID.
  id: e9eb5789-9ac8-4e8c-8901-ffbc609e89a7
  # Pantheon site name.
  site: yalesitesd9sandbox1
tooling:
  drush:
    service: appserver
    env:
      # Set base url based on above Lando project 'name'.
      DRUSH_OPTIONS_URI: "https://yalesites-project.lndo.site/"
