name: yalesites-web-property
recipe: pantheon
config:
  framework: drupal8
  # Disable the SOLR index
  index: false
  # Enable the VARNISH edge
  edge: true
  # Enable the REDIS cache
  cache: true
tooling:
  phpunit:
    service: appserver
    user: www-data
    cmd:
      - appserver: php /app/vendor/bin/phpunit -c /app/phpunit.xml
